"""
Fact-Check Judge Agent.

Uses GPT-OSS-120B (via OpenRouter) to evaluate the sterile Fact Dossier generated by the Evidence Analyst,
and produces the final Verdict, Confidence, and Explanation.
"""

import json
import logging
from typing import Optional
from app.config import settings
from app.services.openrouter_client import get_openrouter_client

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are the Supreme Fact-Check Judge.
Your job is to read a user's claim and a 'Fact Dossier' provided by your researcher.
You have no other knowledge. You MUST base your verdict strictly on the Evidence Analyst's Fact Dossier and the provided Consensus Analysis.

Rules:
1. If sources strongly contradict the claim, mark as FALSE.
2. If sources strongly support the claim, mark as TRUE.
3. If sources conflict OR evidence is weak/insufficient, mark as UNVERIFIED (do NOT use any other label).
4. If evidence partially supports but is incomplete/oversimplified, mark as MISLEADING.
5. Verdict MUST be one of: TRUE, FALSE, MISLEADING, UNVERIFIED.
6. Your explanation MUST include:
   - number of supporting sources (integer)
   - number of contradicting sources (integer)
   - a brief scientific plausibility assessment ("plausible", "implausible", or "unclear") based ONLY on the provided facts.
7. Your explanation must be logical, objective, and cite source names provided in the evidence (e.g., [Reuters]).
8. You MUST respond in pure JSON.

JSON Format:
{
  "verdict": "TRUE" | "FALSE" | "MISLEADING" | "UNVERIFIED",
  "confidence": 0.95,
  "explanation": "Detailed logical reasoning..."
}
"""

def generate_verdict_from_dossier(
    claim: str,
    dossier: str,
    consensus: Optional[dict] = None,
    social: Optional[dict] = None,
) -> dict:
    """
    Evaluates the dossier and generates the final JSON verdict.
    """
    logger.info(f"⚖️ Fact-Check Judge evaluating dossier...")

    if not dossier or len(dossier.strip()) == 0:
        return {
            "verdict": "UNVERIFIED",
            "confidence": 0.0,
            "explanation": "No relevant verifiable facts could be extracted from the retrieved sources."
        }

    try:
        consensus = consensus or {}
        supporting_sources = consensus.get("supporting_sources", 0)
        contradicting_sources = consensus.get("contradicting_sources", 0)
        consensus_label = consensus.get("consensus_label", "inconclusive")

        social = social or {}
        rumor_detected = social.get("rumor_detected", False)
        misinformation_probability = social.get("misinformation_probability", 0.0)
        discussion_volume = social.get("discussion_volume", 0)

        client = get_openrouter_client()
        response = client.chat.completions.create(
            model=settings.MODEL_FACTCHECK_JUDGE,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {
                    "role": "user",
                    "content": (
                        f"CLAIM:\n{claim}\n\n"
                        f"FACT DOSSIER:\n{dossier}\n\n"
                        "CONSENSUS ANALYSIS:\n"
                        f"Supporting sources: {supporting_sources}\n"
                        f"Contradicting sources: {contradicting_sources}\n"
                        f"Consensus label: {consensus_label}\n\n"
                        "SOCIAL SIGNAL ANALYSIS:\n"
                        f"Rumor detected: {rumor_detected}\n"
                        f"Misinformation probability: {misinformation_probability}\n"
                        f"Discussion volume: {discussion_volume}\n\n"
                        "TASK:\nDecide the final verdict.\n\n"
                        "Possible verdicts:\nTRUE\nFALSE\nMISLEADING\nUNVERIFIED\n"
                    ),
                },
            ],
            temperature=0.2,
            max_tokens=800,
        )

        content = response.choices[0].message.content.strip()
        
        try:
            if "```json" in content:
                content = content.split("```json")[1].split("```")[0].strip()
            elif "```" in content:
                content = content.split("```")[1].split("```")[0].strip()
                
            result = json.loads(content)
            
            verdict = str(result.get("verdict", "UNVERIFIED")).upper()
            if verdict == "DISPUTED":
                verdict = "UNVERIFIED"
            if verdict not in ["TRUE", "FALSE", "MISLEADING", "UNVERIFIED"]:
                verdict = "UNVERIFIED"
                
            logger.info(f"✅ Judge generated verdict: {verdict}")
            
            return {
                "verdict": verdict,
                "confidence": float(result.get("confidence", 0.5)),
                "explanation": str(result.get("explanation", "No reasoning provided."))
            }
                
        except json.JSONDecodeError:
            logger.warning("Fact-Check Judge failed to return valid JSON.")
            return {
                "verdict": "UNVERIFIED",
                "confidence": 0.5,
                "explanation": content
            }

    except Exception as e:
        logger.error(f"❌ Fact-Check Judge failed: {e}")
        return {
            "verdict": "UNVERIFIED",
            "confidence": 0.0,
            "explanation": f"Evaluation error: {str(e)}"
        }
